[package]
name = "controller"
version = "0.4.0"
authors = ["clux <sszynrae@gmail.com>"]
edition = "2018"

[[bin]]
doc = false
name = "controller"
path = "src/main.rs"

[lib]
name = "controller"
path = "src/lib.rs"

[dependencies]
actix-rt = "1.1.0"
actix-web = "2.0.0"
futures = "0.3.1"
futures-util = "0.3.5"
tokio = { version = "0.2.21", features = ["full"] }
prometheus = "0.7.0"
#kube = { version = "0.36.0", features = [] }
#kube-runtime = "0.36.0"
#kube-derive = "0.36.0"
kube = { git = "https://github.com/teozkr/kube-rs", rev = "1beb0f4da2384c39a0ad1dc590f4c972fe438f59" }
kube-derive = { git = "https://github.com/teozkr/kube-rs", rev = "1beb0f4da2384c39a0ad1dc590f4c972fe438f59" }
kube-runtime = { git = "https://github.com/teozkr/kube-rs", rev = "1beb0f4da2384c39a0ad1dc590f4c972fe438f59" }
k8s-openapi = { version = "0.9.0", features = ["v1_17"], default-features=false }
serde = "1.0.94"
serde_derive = "1.0.94"
serde_json = "1.0.56"
chrono = { version = "0.4.7", features = ["serde"] }
log = "0.4.6"
env_logger = "0.7.1"
color-eyre = "0.5.0"
snafu = "0.6.8"
