[package]
name = "controller"
version = "0.2.0"
authors = ["clux <sszynrae@gmail.com>"]
edition = "2018"

[[bin]]
doc = false
name = "controller"
path = "src/main.rs"

[lib]
name = "controller"
path = "src/lib.rs"

[dependencies]
kube = { git = "https://github.com/clux/kube-rs", rev = "517791cc0d97485ae5519043ed51f81c0dabe92e" }
#kube = { path = "../kube-rs" }
#kube = "0.7.0"
actix-web = "1.0.0-beta.2"
actix = "0.8.1"
serde = "1.0.90"
serde_derive = "1.0.90"
failure = "0.1.5"
log = "0.4.6"
env_logger = "0.6.1"
