[package]
name = "controller"
version = "0.5.0"
authors = ["clux <sszynrae@gmail.com>"]
edition = "2018"

[[bin]]
doc = false
name = "controller"
path = "src/main.rs"

[lib]
name = "controller"
path = "src/lib.rs"

[dependencies]
actix-rt = "1.1.0"
actix-web = "2.0.0"
futures = "0.3.5"
tokio = { version = "0.2.21", features = ["macros"] }
prometheus = "0.9.0"
kube = "0.37.0"
kube-runtime = "0.37.0"
kube-derive = "0.37.0"
k8s-openapi = { version = "0.9.0", features = ["v1_17"], default-features=false }
serde = "1.0.94"
serde_derive = "1.0.94"
serde_json = "1.0.56"
chrono = { version = "0.4.7", features = ["serde"] }
color-eyre = "0.5.0"
snafu = "0.6.8"
tracing = "0.1.16"
tracing-subscriber = "0.2.8"
