[package]
name = "controller"
version = "0.7.0"
authors = ["clux <sszynrae@gmail.com>"]
edition = "2018"
default-run = "controller"

[[bin]]
doc = false
name = "controller"
path = "src/main.rs"

[[bin]]
doc = false
name = "crdgen"
path = "src/crdgen.rs"

[lib]
name = "controller"
path = "src/lib.rs"

[dependencies]
actix-rt = "1.1.1"
actix-web = "3.0.0"
futures = "0.3.5"
tokio = { version = "0.2.22", features = ["macros"] }
prometheus = "0.10.0"
#kube = { version = "0.42.0", features = ["derive"] }
#kube-runtime = "0.42.0"
kube = { git = "https://github.com/clux/kube-rs.git", rev = "640bb11b0d2763eefac54064fdf436ce9eb097c8", features = ["derive"] }
kube-runtime = { git = "https://github.com/clux/kube-rs.git", rev = "640bb11b0d2763eefac54064fdf436ce9eb097c8" }
k8s-openapi = { version = "0.10.0", features = ["v1_19"], default-features=false }
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0.57"
chrono = { version = "0.4.15", features = ["serde"] }
color-eyre = "0.5.2"
snafu = "0.6.8"
tracing = "0.1.19"
tracing-subscriber = "0.2.11"
tracing-futures = "0.2.4"
schemars = "0.8.0"
serde_yaml = "0.8.14"
