[package]
name = "controller"
version = "0.8.0"
authors = ["clux <sszynrae@gmail.com>"]
edition = "2018"
default-run = "controller"

[[bin]]
doc = false
name = "controller"
path = "src/main.rs"

[[bin]]
doc = false
name = "crdgen"
path = "src/crdgen.rs"

[lib]
name = "controller"
path = "src/lib.rs"

[dependencies]
actix-rt = "1.1.1"
actix-web = "3.3.2"
futures = "0.3.8"
tokio = { version = "0.2.24", features = ["macros"] }
prometheus = "0.11.0"
kube = { version = "0.44.0", features = ["derive"] }
kube-runtime = "0.44.0"
#kube = { git = "https://github.com/clux/kube-rs.git", rev = "640bb11b0d2763eefac54064fdf436ce9eb097c8", features = ["derive"] }
#kube-runtime = { git = "https://github.com/clux/kube-rs.git", rev = "640bb11b0d2763eefac54064fdf436ce9eb097c8" }
k8s-openapi = { version = "0.10.0", features = ["v1_19"], default-features=false }
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.60"
chrono = { version = "0.4.19", features = ["serde"] }
color-eyre = "0.5.10"
snafu = "0.6.10"
tracing = "0.1.22"
tracing-subscriber = "0.2.15"
tracing-futures = "0.2.4"
schemars = { version = "0.8.0", features = ["chrono"] }
serde_yaml = "0.8.14"
