[package]
name = "controller"
version = "0.8.0"
authors = ["clux <sszynrae@gmail.com>"]
edition = "2018"
default-run = "controller"

[[bin]]
doc = false
name = "controller"
path = "src/main.rs"

[[bin]]
doc = false
name = "crdgen"
path = "src/crdgen.rs"

[lib]
name = "controller"
path = "src/lib.rs"

[dependencies]
actix-rt = "2.1.0"
actix-web = "4.0.0-beta.1"
futures = "0.3.13"
tokio = { version = "1.1.0", features = ["macros"] }
prometheus = "0.12.0"
kube = { version = "0.51.0", features = ["derive"] }
kube-runtime = "0.51.0"
k8s-openapi = { version = "0.11.0", features = ["v1_19"], default-features=false }
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1.0.64"
chrono = { version = "0.4.19", features = ["serde"] }
color-eyre = "0.5.10"
snafu = "0.6.10"
tracing = "0.1.25"
tracing-subscriber = { version = "0.2.16", features = ["json"] }
tracing-futures = "0.2.5"
schemars = { version = "0.8.0", features = ["chrono"] }
serde_yaml = "0.8.17"

# local dev
#kube = { path = "../kube-rs/kube", features = ["derive"] }
#kube-runtime = { path = "../kube-rs/kube-runtime" }
