[package]
name = "controller"
version = "0.5.0-alpha1"
authors = ["clux <sszynrae@gmail.com>"]
edition = "2018"

[[bin]]
doc = false
name = "controller"
path = "src/main.rs"

[lib]
name = "controller"
path = "src/lib.rs"

[dependencies]
kube = { git = "https://github.com/clux/kube-rs", rev = "16a48691ac290a94d68af251150df0918dc77aeb", features = [] }
actix-web = "1.0.8"
actix = "0.8.3"
serde = "1.0.102"
serde_derive = "1.0.102"
failure = "0.1.6"
log = "0.4.8"
env_logger = "0.7.1"
chrono = { version = "0.4.9", features = ["serde"] }
prometheus = "0.7.0"
tokio = { version = "=0.2.0-alpha.6" }
