[package]
name = "controller"
version = "0.4.0"
authors = ["clux <sszynrae@gmail.com>"]
edition = "2018"

[[bin]]
doc = false
name = "controller"
path = "src/main.rs"

[lib]
name = "controller"
path = "src/lib.rs"

[dependencies]
kube = { version = "0.36.0", features = [] }
kube-runtime = "0.36.0"
#kube = { git = "https://github.com/clux/kube-rs", rev = "f375ca38a82146c4616d8a162879c46fec60d420" }
k8s-openapi = { version = "0.8.0", features = ["v1_17"], default-features=false }
actix-web = "2.0.0"
serde = "1.0.94"
serde_derive = "1.0.94"
anyhow = "1.0.25"
log = "0.4.6"
env_logger = "0.7.1"
chrono = { version = "0.4.7", features = ["serde"] }
prometheus = "0.7.0"
futures = "0.3.1"
tokio = "0.2.4"
futures-util = "0.3.5"
