[package]
name = "controller"
version = "0.8.0"
authors = ["clux <sszynrae@gmail.com>"]
edition = "2018"
default-run = "controller"

[[bin]]
doc = false
name = "controller"
path = "src/main.rs"

[[bin]]
doc = false
name = "crdgen"
path = "src/crdgen.rs"

[[bin]]
doc = false
name = "blah"
path = "blah.rs"

[lib]
name = "controller"
path = "src/lib.rs"

[dependencies]
actix-rt = "2.1.0"
actix-web = "4.0.0-beta.1"
futures = "0.3.13"
tokio = { version = "1.1.0", features = ["macros"] }
prometheus = "0.12.0"
#kube = { version = "0.51.0", features = ["derive"] }
#kube-runtime = "0.51.0"
k8s-openapi = { version = "0.11.0", features = ["v1_19"], default-features=false }
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1.0.64"
chrono = { version = "0.4.19", features = ["serde"] }
thiserror = "1.0.24"
schemars = { version = "0.8.0", features = ["chrono"] }
serde_yaml = "0.8.17"
tracing = "0.1.25"
tracing-subscriber = { version = "0.2.16", features = ["json"] }
tracing-futures = "0.2.5"
tracing-opentelemetry = "0.11.0"
opentelemetry = { version = "0.12.0", features = ["trace"] }
opentelemetry-otlp = { version = "0.5.0", features = ["tokio", "grpc-sys", "openssl"], default-features=false }
#opentelemetry-otlp = { version = "0.5.0", features = ["tokio", "async"] }

# local dev
#kube = { path = "../kube-rs/kube", features = ["derive"] }
#kube-runtime = { path = "../kube-rs/kube-runtime" }
kube = { git = "https://github.com/clux/kube-rs.git", branch = "tracing-test", features = ["derive"] }
kube-runtime = { git = "https://github.com/clux/kube-rs.git", branch = "tracing-test" }
