[package]
name = "operator"
version = "0.1.0"
authors = ["clux"]
edition = "2018"

[[bin]]
doc = false
name = "operator"
path = "src/main.rs"

[lib]
name = "operator"
path = "src/lib.rs"

[dependencies]
kubernetes = { git = "https://github.com/clux/kubernetes-rust", rev = "751dd215ce6813dae06aa0782bbe0ae4e6ecbc08" }
#kubernetes = { path = "../kubernetes-rust" }
actix-web = "1.0.0-beta.2"
actix = "0.8.1"
serde = "1.0.90"
serde_derive = "1.0.90"
failure = "0.1.5"
#sentry = "0.15.4"
#sentry-actix = "0.15.4"
log = "0.4.6"
env_logger = "0.6.1"
