[package]
name = "controller"
version = "0.4.0"
authors = ["clux <sszynrae@gmail.com>"]
edition = "2018"

[[bin]]
doc = false
name = "controller"
path = "src/main.rs"

[lib]
name = "controller"
path = "src/lib.rs"

[dependencies]
kube = { version = "0.13.0", features = [] }
actix-web = "1.0.3"
actix = "0.8.3"
serde = "1.0.94"
serde_derive = "1.0.94"
failure = "0.1.5"
log = "0.4.6"
env_logger = "0.6.1"
chrono = { version = "0.4.7", features = ["serde"] }
prometheus = "0.7.0"
