---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller
  namespace: foo-controller

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: foo-controller
rules:
- apiGroups: ["imjasonh.dev"]
  resources: ["foos", "foos/status"]
  verbs: ["list", "get", "watch", "create", "delete", "patch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: foo-controller
subjects:
- kind: ServiceAccount
  name: controller
  namespace: foo-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: foo-controller
