---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clux
  namespace: default

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: control-foos
rules:
- apiGroups: ["clux.dev"]
  resources: ["foos", "foos/status"]
  verbs: ["list", "get", "watch", "create", "delete", "patch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: foobbar-view
subjects:
- kind: ServiceAccount
  name: clux-foo-access
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: control-foos
